#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H


#include <QLoggingCategory>
#include "logger-core_global.h"

LOGGERCORESHARED_EXPORT Q_DECLARE_LOGGING_CATEGORY(logDebug)
LOGGERCORESHARED_EXPORT Q_DECLARE_LOGGING_CATEGORY(logInfo)
LOGGERCORESHARED_EXPORT Q_DECLARE_LOGGING_CATEGORY(logWarning)
LOGGERCORESHARED_EXPORT Q_DECLARE_LOGGING_CATEGORY(logCritical)
LOGGERCORESHARED_EXPORT Q_DECLARE_LOGGING_CATEGORY(logFatal)


class LOGGERCORESHARED_EXPORT LoggingCategories
{
public:
    LoggingCategories(){}
};

#endif // LOGGINGCATEGORIES_H
